name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      YC_CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Проверить наличие образа
        run: |
          echo "Проверьте вручную, что образ cr.yandex/${{ secrets.YC_CR_REGISTRY }}/app:${{ github.event.inputs.release_version }}_latest есть в Container Registry"
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 84.201.151.208
          username: z4r4pro
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull cr.yandex/${{ secrets.YC_CR_REGISTRY }}/app:${{ github.event.inputs.release_version }}_latest
            docker stop shri-infra || true
            docker rm shri-infra || true
            docker run -d --name shri-infra -p 3000:3000 cr.yandex/${{ secrets.YC_CR_REGISTRY }}/app:${{ github.event.inputs.release_version }}_latest
      - uses: actions/checkout@v4
      - name: Comment to Issue
        run: |
          gh issue comment $(gh issue list --search "Release v${{ github.event.inputs.release_version }}" --json number --jq '.[0].number') \
            --body $'Релиз выкачен в прод: '"$(date)"$'\nАвтор: '"${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
