name: Fix Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

jobs:
  fix:
    runs-on: ubuntu-latest
    env:
      YC_CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY }}
      YC_CR_TOKEN: ${{ secrets.YC_CR_TOKEN }}
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      FIX_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: releases/${{ env.RELEASE_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ env.YC_CR_REGISTRY }}/app:${RELEASE_VERSION}_fix${FIX_NUMBER} .
          docker tag cr.yandex/${{ env.YC_CR_REGISTRY }}/app:${RELEASE_VERSION}_fix${FIX_NUMBER} cr.yandex/${{ env.YC_CR_REGISTRY }}/app:${RELEASE_VERSION}_latest
      - name: Login to Yandex Container Registry
        run: echo $YC_CR_TOKEN | docker login --username oauth --password-stdin cr.yandex
      - name: Push Docker images
        run: |
          docker push cr.yandex/${{ env.YC_CR_REGISTRY }}/app:${RELEASE_VERSION}_fix${FIX_NUMBER}
          docker push cr.yandex/${{ env.YC_CR_REGISTRY }}/app:${RELEASE_VERSION}_latest
      - name: Create fix tag
        run: |
          git tag v${RELEASE_VERSION}_fix${FIX_NUMBER}
          git push origin v${RELEASE_VERSION}_fix${FIX_NUMBER}
      - name: Comment to Issue
        run: |
          gh issue comment $(gh issue list --search "Release v${RELEASE_VERSION}" --json number --jq '.[0].number') --body "Дата фикса: $(date)\nАвтор: ${{ github.actor }}\nDocker: cr.yandex/${{ env.YC_CR_REGISTRY }}/app:${RELEASE_VERSION}_fix${FIX_NUMBER}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
